backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "project" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Projects" # Used in the UI, ie.: "New Post"
    folder: "site/content/project" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Client Name", name: "title", widget: "string"}
      - {label: "Heading Blurb", name: "headingBlurb", widget: "text"}
      - {label: "Intro Blurb", name: "introBlurb", widget: "text"}
      - {label: "Hero Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: 'Color - Hex Code: "#123456"', name: color, widget: string}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "homepage"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Type, name: type, widget: hidden, default: homepage}
          - {label: Page, name: page, widget: hidden, default: "/index.html"}
          - {label: Intro Copy - Part 1, name: introCopyPart1, widget: string}
          - {label: Featured Case Studies, name: caseStudies, widget: list, fields: [{label: Title, name: title, widget: markdown}, {label: Client Name, name: client, widget: string}, {label: Image, name: image, widget: image}, {label: 'Color - Hex Code: "#123456"', name: color, widget: string}]}
